version: '3.8'

services:
  laravel-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: meufinanceiro_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - meufinanceiro-network
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: meufinanceiro_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: meufinanceiro
      POSTGRES_USER: finance_user
      POSTGRES_PASSWORD: finance_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - meufinanceiro-network

  nginx:
    image: nginx:alpine
    container_name: meufinanceiro_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - laravel-app
    networks:
      - meufinanceiro-network

networks:
  meufinanceiro-network:
    driver: bridge

volumes:
  pgdata:
